# Compiler settings
CXX = g++
CXXFLAGS = -std=c++11 -Wall -g  # Enable C++11, show all warnings, and include debug symbols


build:
	clear ; g++ *.cpp -std=c++11 -Wall -g

r:
	./a.out

#------------------------------------------------------------------------------
# Object files
#------------------------------------------------------------------------------
# DFA.o: DFA.h DFA.cpp
# 	$(CXX) -o (CXXFLAGS) DFA.cpp -c -o DFA.o

# NFA.o: NFA.h NFA.cpp
# 	$(CXX) -o (CXXFLAGS) NFA.cpp -c -o NFA.o

# REGEX.o: REGEX.h REGEX.cpp
# 	$(CXX) -o (CXXFLAGS) REGEX.cpp -c -o REGEX.o



